Binder
NEMRI-org/primo-optimizer pull request #25
Opened 2024-09-14 17:49 UTC by apd-ypuranik

## Fixes/Addresses/Summary/Motivation:

Sets up the Binder environment to allow anyone to run PRIMO examples without having to download/install software locally

## Changes proposed in this PR:
- Set up Binder configuration in .binder folder
- Add a short README document in the .binder folder

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my
contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md file
   at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has
   rights to intellectual property that includes these contributions, I represent that I have
   received permission to make contributions and grant the required license on behalf of that
   employer.

2024-09-16 12:26 UTC, radhakrishnatg commented on .binder/README.md
> +You can run PRIMO with [Binder](https://mybinder.org): a public cloud service that provides a temporary and shot-lived sandbox environment to run PRIMO without installing any software locally.
*short*-lived

2024-09-16 12:26 UTC, radhakrishnatg commented on .binder/README.md
> +* The Binder provided environment is **public and insecure**. Please do not use this environment to work with sensitive data.
Binder-provided?

2024-09-16 12:27 UTC, radhakrishnatg requested changes
Minor typo

2024-10-04 02:50 UTC, apd-ypuranik commented
Skipping pull request in favor of a new and cleaner one to be opened separately

2024-10-04 02:50 UTC, closed without merging